# Generated by Django 4.2.1 on 2023-06-01 11:13

import SchoolApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='salaire',
            name='type_emploi',
        ),
        migrations.AlterField(
            model_name='paiement',
            name='date_paiement',
            field=models.DateField(default=SchoolApp.models.Paiement.get_today_date),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='mois_paiement',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='type_service',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='mois_paiement',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
