# Generated by Django 4.2.1 on 2023-06-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0002_remove_paiement_admin_remove_paiement_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='reference',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
