# Generated by Django 4.2.1 on 2023-06-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0003_alter_paiement_montant_alter_paiement_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaire',
            name='reference',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
