# Generated by Django 4.2.1 on 2023-06-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0004_alter_salaire_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devoir',
            name='contenu',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
