# Generated by Django 4.2.1 on 2023-06-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0005_alter_devoir_contenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devoir',
            name='id_devoir',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
