# Generated by Django 4.2.1 on 2023-06-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0009_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='link',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='platform',
            field=models.CharField(choices=[('zoom', 'Zoom'), ('google_meet', 'Google Meet')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
