# Generated by Django 4.2.1 on 2023-06-05 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0010_session_date_session_link_session_platform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Se_Comporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epreuve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.epreuve')),
                ('sousmatiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.sousmatiere')),
            ],
        ),
    ]
