# Generated by Django 4.2.1 on 2023-06-06 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0011_se_comporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevoirContenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CNE_eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.eleve')),
                ('Id_devoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.devoir')),
            ],
        ),
    ]
