# Generated by Django 4.2.1 on 2023-06-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0012_devoircontenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='devoir',
            name='students',
            field=models.ManyToManyField(through='SchoolApp.DevoirContenue', to='SchoolApp.eleve'),
        ),
    ]
