# Generated by Django 4.2.1 on 2023-06-09 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0015_eprv'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='pdf_cours',
            field=models.FileField(null=True, upload_to='courspdf/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='semester',
            name='annee_scolaire',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='semester',
            name='date_debut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='semester',
            name='date_fin',
            field=models.DateField(),
        ),
    ]
