# Generated by Django 4.2.1 on 2023-06-09 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0016_cours_pdf_cours_alter_semester_annee_scolaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='emploie_temps',
            field=models.FileField(null=True, upload_to='emplois_temps/', validators=[django.core.validators.FileExtensionValidator(['xls', 'xml', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='cours',
            name='id_cours',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
