# Generated by Django 4.2.1 on 2023-06-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0017_alter_classe_emploie_temps_alter_cours_id_cours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='nom_matiere',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
