# Generated by Django 4.2.1 on 2023-06-10 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0018_alter_matiere_nom_matiere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devoir',
            name='students',
        ),
        migrations.AddField(
            model_name='devoir',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.classe'),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='id_devoir',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
