# Generated by Django 4.2.1 on 2023-06-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0019_remove_devoir_students_devoir_classe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epreuve',
            name='nom_epreuve',
            field=models.IntegerField(choices=[(1, 'epreuve 1'), (2, 'epreuve 2'), (3, 'epreuve 3'), (4, 'epreuve 4'), (5, 'epreuve 5'), (6, 'epreuve 6')]),
        ),
    ]
