# Generated by Django 4.2.1 on 2023-06-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0020_alter_epreuve_nom_epreuve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='id_cours',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
