# Generated by Django 4.2.1 on 2023-07-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0022_alter_classe_nbr_eleve_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='max_students',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='classe',
            name='nbr_eleve_classe',
            field=models.IntegerField(),
        ),
    ]
