# Generated by Django 4.2.1 on 2023-07-08 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0023_classe_max_students_alter_classe_nbr_eleve_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='nbr_eleve_classe',
        ),
    ]
