# Generated by Django 4.2.1 on 2023-07-08 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0024_remove_classe_nbr_eleve_classe'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_connected', models.PositiveIntegerField(default=0)),
                ('compte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.compte')),
            ],
        ),
    ]
